version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  pre_build:
    commands:
      - echo "pre build"
  build:
    commands:
      - npm run build
      - npm run export
      - echo "building..."
  post_build:
    commands:
      - aws s3 sync --delete ./out/ "s3://www.avana.id" --cache-control max-age=31536000 --expires 31536000
        - aws cloudfront create-invalidation --distribution-id EL2E3BOU4C4D2 --paths "/*"
cache:
  paths:
    - "node_modules/**/*"
