version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  pre_build:
    commands:
      - echo "pre build"
  build:
    commands:
      - npm run build
      - npm run export
      - echo "building..."
  post_build:
    commands:
      - aws s3 sync --delete ./out/ "s3://landing-my.avana.link" --cache-control max-age=0,no-cache,no-store,must-revalidate
      - aws cloudfront create-invalidation --distribution-id E31SJQU66I3XIQ --paths "/*"
cache:
  paths:
    - "node_modules/**/*"
